// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgxbkrsheaK2ZXFrz9CRMT0P0TZvF3UuU',
    appId: '1:316847997090:web:962289675a2768c08d57fb',
    messagingSenderId: '316847997090',
    projectId: 'bheri-446306',
    authDomain: 'bheri-446306.firebaseapp.com',
    storageBucket: 'bheri-446306.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhSZz0YObP6cXY5ti3bXApG8TAgUAnZKY',
    appId: '1:316847997090:android:5c482d90835a57038d57fb',
    messagingSenderId: '316847997090',
    projectId: 'bheri-446306',
    storageBucket: 'bheri-446306.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0909KXwRqhSiORnLegfzfUdLx9kvrJTk',
    appId: '1:316847997090:ios:05bfd32476309ad28d57fb',
    messagingSenderId: '316847997090',
    projectId: 'bheri-446306',
    storageBucket: 'bheri-446306.firebasestorage.app',
    androidClientId: '316847997090-rq6reduc42g6qu8lta3l0r8kcj2mfvdt.apps.googleusercontent.com',
    iosBundleId: 'in.bheri.dhara',
  );
}
